const Router = require('express')
const router = new Router()
const deviceRouter = require('./deviceRouter')
const userRouter = require('./userRouter')
const brandRouter = require('./brandRouter')
const typeRouter = require('./typeRouter')
const furnitureRouter = require('./furnitureRouter')
const orderRouter = require('./orderRouter')
const participantRouter = require('./participantRouter')
const blobRouter = require('./blobRouter')
const searchRouter = require('./searchRouter')

router.use('/user', userRouter)
router.use('/type', typeRouter)
router.use('/brand', brandRouter)
router.use('/device', deviceRouter)
router.use('/blob', blobRouter)
router.use('/furniture', furnitureRouter)
router.use('/participant', participantRouter)
router.use('/order', orderRouter)
router.use('/search', searchRouter)

module.exports = router